### ISSUE TITLE
Failed to create index

### ISSUE THREAD

**Issue by cantv6605-seta** [cychiuae/casbin-pg-adapter#2]
I'm using DB with some schemas.
How can I create new cabin table in a schema DB?
I tried and got an error message:
with tableName = "ABC.auth_permission"
Cannot create index for column: p_type. Error: pq: syntax error at or near "."

Index query like: CREATE INDEX IF NOT EXISTS idx_ABC.auth_permission_p_type ON ABC.auth_permission (p_type)

Please help to fix it. Thanks!

**Comment by cantv6605-seta** [comment]
@cychiuae Could you take a look at my issue?

**Comment by cychiuae** [comment]
Hi @cantv6605-seta,

Thanks for your comment. I have released `v0.0.5` to support usage of db schema. 

Hope it can help you.

**Comment by cantv6605-seta** [comment]
Thank you!
