### ISSUE TITLE
Support policy subset loading

### ISSUE THREAD

**Issue by fgblomqvist** [cychiuae/casbin-pg-adapter#3]
https://casbin.org/docs/en/policy-subset-loading

I can submit a PR for this if you're open to reviewing one.

**Comment by hsluoyz** [comment]
@closetool can you take a look at this issue?

**Comment by kilosonc** [comment]
sure

**Comment by hsluoyz** [comment]
PR proposed: https://github.com/cychiuae/casbin-pg-adapter/pull/6
