### ISSUE TITLE
Please don't change tags randomly, that change broke my dependencies 

### ISSUE THREAD

**Issue by Vanclief** [cychiuae/casbin-pg-adapter#9]
I woke up today to see our CI was failing:

`github.com/casbin/casbin-pg-adapter@v0.1.5: invalid version: unknown revision v0.1.5`

Seems for some reason you changed versions to remove the `0.1.5` for `0.0.5.` 

Please don't rewrite tag history as go mod depends on that for versioning and managing dependencies, and on top of that it defeats the purpose of using versioning in the first place.

**Comment by hsluoyz** [comment]
Hi @Vanclief , sorry for confusion here. It has nothing to do with this repo (which has the same name). We have restored the previous versions: https://github.com/casbin/casbin-pg-adapter/releases/tag/v0.1.5

You can restart the CI and it should be fixed.

**Comment by Vanclief** [comment]
Hi @hsluoyz, 

In the confusion I commented on this repo as the main `https://github.com/casbin/casbin-pg-adapter/` was marked "read only". I thought it was moving over here. 

Thank you
